### ISSUE TITLE
GRC example freezes (unbalanced streams) 

### ISSUE THREAD

**Issue by AsriFox** [igorauad/gr-dvbs2rx#23] opened 2023-05-18 14:28 UTC
When using [dvbs2_fec_ber.grc](https://github.com/igorauad/gr-dvbs2rx/blob/9196783147266d216e41b798e1a241766bcab66f/examples/dvbs2_fec_ber.grc) to simulate the protocol, I have discovered that only MODCOD=QPSK1/4 works. Any other variant makes the simulation stuck.

This seems to be an issue with multiple-input blocks, like BER and QT GUI Time Sink; if the streams have unbalanced rates, it locks up. Adding a buffer on the faster stream seems to solve the problem:
![Flowgraph with the throttle buffer on the input stream](https://github.com/igorauad/gr-dvbs2rx/assets/91423563/10ac6f0e-494e-4ae4-be1d-4f1b6309aca5)
On this flowgraph, the Throttle block is set to have an extended output buffer:
![Throttle Properties Advanced Minoutbuf=64800*32](https://github.com/igorauad/gr-dvbs2rx/assets/91423563/0db6e6a3-6bda-4434-b57d-80781da3bbcd)

With the addition of the buffer block, the flowgraph is confirmed to work with all supported MODCODs.

**Comment by igorauad** [comment] 2023-05-18 18:46
Hi @AsriFox ,

Thanks. Interesting issue and workaround. I would need some time to investigate this in detail, but here are some initial thoughts:

- The problem may arise for higher code rates because the message length (Kbch) increases. For example, for QPSK1/4 normal FECFRAME, Kbch equals 16008 bits (2001 bytes). Now, for instance, for a higher rate like QPSK3/5, Kbch increases to 38688 bits (4836 bytes), so it takes more time until the `out_bytes` source sees some bytes (because the entire message comes at once), whereas the `in_bytes` has data from the start. That creates the imbalance you mentioned.
- I quickly went and saw that the BER block was the culprit. By disabling it, the flowgraph works. As you indicated, it looks like an issue with multiple-input blocks, like the BER block.
- I had a quick look at the BER block's implementation, and I see some potentially problematic aspects:
    1. Its implementation does not have a `forecast` function. That means it uses the default forecast function, which assumes 1:1 correspondence between the input samples required for a target number of output samples.
    2. Its work function always outputs a single sample, no matter how many input samples are provided. Hence, the default forecast function does not apply to it at all. For instance, if the forecast function asks how many input samples are required to output 1024 samples, the default implementation would say 1024 input samples. Meanwhile, only a single output sample is produced when the work function is called with 1024 input samples. Besides, with this implementation, there is no way to tell how many input samples are required, which is likely why the forecast function was not implemented in the first place. 

When I have time to investigate this, I will see if I can solve the problem by adapting the implementation of the BER block. But, in the meantime, I can confirm your workaround is good enough.

**Comment by igorauad** [comment] 2023-12-01 21:48
@AsriFox I'm cleaning up the issues that have been pending in the repo for a long time. So I'll close this.

Please do not hesitate to reach out or open another issue if you are still interested in exploring the project.

Thanks

**Closed as completed by igorauad** 2023-12-01 21:48 UTC
